Server/Pages/Account/User/ChangeCellPhoneNumber.cshtml.cs
namespace Server.Pages.Security.User
{
	[Microsoft.AspNetCore.Authorization.Authorize]
	public class ChangeCellPhoneNumberModel : Infrastructure.BasePageModel
	{
		public ChangeCellPhoneNumberModel() : base()
		{
			ViewModel = new();
		}

		[Microsoft.AspNetCore.Mvc.BindProperty]
		protected ViewModels.Pages.Account.Users.ChangeCellPhoneNumberViewModel ViewModel { get; set; }

		public void OnGet()
		{
		}
	}
}

Server/Pages/Account/User/ChangeEmailAddress.cshtml.cs
namespace Server.Pages.Security.User
{
	[Microsoft.AspNetCore.Authorization.Authorize]
	public class ChangeEmailAddressModel : Infrastructure.BasePageModel
	{
		public ChangeEmailAddressModel() : base()
		{
			ViewModel = new();
		}

		[Microsoft.AspNetCore.Mvc.BindProperty]
		protected ViewModels.Pages.Account.Users.ChangeEmailAddressViewModel ViewModel { get; set; }

		public void OnGet()
		{
		}
	}
}

Server/Pages/Account/User/ChangePassword.cshtml.cs
namespace Server.Pages.Security.User
{
	[Microsoft.AspNetCore.Authorization.Authorize]
	public class ChangePasswordModel : Infrastructure.BasePageModel
	{
		public ChangePasswordModel() : base()
		{
			ViewModel = new();
		}

		[Microsoft.AspNetCore.Mvc.BindProperty]
		protected ViewModels.Pages.Account.Users.ChangePasswordViewModel ViewModel { get; set; }

		public void OnGet()
		{
		}
	}
}

Server/Pages/Account/User/Update.cshtml.cs
using Application.UserApp;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Resources;
using System;
using System.Linq;
using System.Threading.Tasks;
using ViewModels.Pages.Admin.Users;

namespace Server.Pages.Account.User;

[Authorize]

public class UpdateModel : BasePageModel
{
    private readonly IUserApplication _application;

    public UpdateModel(IUserApplication application)
    {
        _application = application;
        ViewModel = new();
    }

    [BindProperty]
    public UpdateViewModel ViewModel { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        Guid id = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id").Value);

        if (id == null)
        {
            AddToastError(Resources.Messages.Errors.IdIsNull);

            return RedirectToPage("/Index");
        }

        ViewModel = (await _application.GetUser(id)).Data;

        if (ViewModel == null)
        {
            AddToastError(Resources.Messages.Errors.ThereIsNotAnyDataWithThisId);

            return RedirectToPage("/Index");
        }

        AddPageWarning(Resources.Messages.Errors.Completeyourinformationbeforeordering);

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ModelState.IsValid == false)
        {
            return Page();
        }

        ViewModel.Role = "User";
        var res = await _application.UpdateUser(ViewModel);

        if (res.Succeeded == false || res.ErrorMessages.Count() > 0)
        {
            foreach (var item in res.ErrorMessages)
            {
                AddToastError(item);
            }

            return Page();
        }

        var successMessage = string.Format(Resources.Messages.Successes.Yourinformationhasbeeneditedsuccessfully);

        AddToastSuccess(successMessage);

        return RedirectToPage("/Index");
    }
}

Server/Pages/Admin/Users/Create.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.UserApp;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Resources;
using ViewModels.Pages.Admin.Users;
using ViewModels.Shared;

namespace Server.Pages.Admin.Users
{

	[Authorize(Roles = Constants.Role.Admin)]
	public class CreateModel : BasePageModel
	{
		public CreateModel(IUserApplication userApplication)
		{
			UserApplication = userApplication;
			UserApplication = userApplication;
			ViewModel = new();

			RolesViewModel = new List<ValueNameViewModel>();
		}

		private IUserApplication UserApplication { get; }
		public IList<ValueNameViewModel> RolesViewModel { get; private set; }

		[BindProperty]
		public CreateViewModel ViewModel { get; set; }

		public async Task OnGetAsync()
		{
			var roles = typeof(Constants.Role).GetFields();

			foreach (var role in roles)
			{
				RolesViewModel.Add(new ValueNameViewModel()
				{
					Name = role.Name,
					Value = role.Name,
				});
			}
		}

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid == false)
			{
				return Page();
			}

			var res = await UserApplication.AddUser(ViewModel);

			if (res.Succeeded == false || res.ErrorMessages.Count() > 0)
			{
				foreach (var item in res.ErrorMessages)
				{
					AddToastError(item);
				}

				return Page();
			}

			var successMessage = string.Format(Resources.Messages.Successes.Created, DataDictionary.User);

			AddToastSuccess(successMessage);

			return RedirectToPage("Index");
		}

	}
}

Server/Pages/Admin/Users/Delete.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Application.UserApp;
using Domain.SeedWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ViewModels.Pages.Admin.Users;

namespace Server.Pages.Admin.Users;

[Microsoft.AspNetCore.Authorization.Authorize
	(Roles = Infrastructure.Constants.Role.Admin)]
public class DeleteModel : Infrastructure.BasePageModel
{
	public DeleteModel(ILogger<DeleteModel> logger,
		IUserApplication userApplication)
	{
		Logger = logger;
		UserApplication = userApplication;
		ViewModel = new();
	}

	private ILogger<DeleteModel> Logger { get; }
	public IUserApplication UserApplication { get; }

	[BindProperty]
	public ViewModels.Pages.Admin.Users.DetailsViewModel ViewModel { get; private set; }

	public async Task<IActionResult> OnGetAsync(Guid? id)
	{
		try
		{
			if (id.HasValue == false)
			{
				AddToastError
					(message: Resources.Messages.Errors.IdIsNull);

				return RedirectToPage(pageName: "Index");
			}

			ViewModel = (await UserApplication.GetUser(id.Value)).Data;

			if (ViewModel == null)
			{
				AddToastError
					(message: Resources.Messages.Errors.ThereIsNotAnyDataWithThisId);

				return RedirectToPage(pageName: "Index");
			}

			return Page();
		}
		catch (System.Exception ex)
		{
			Logger.LogError
				(message: Constants.Logger.ErrorMessage, args: ex.Message);

			AddToastError
				(message: Resources.Messages.Errors.UnexpectedError);

			return RedirectToPage(pageName: "Index");
		}

	}

	public async Task<IActionResult> OnPostAsync(Guid? id)
	{
		if (id.HasValue == false)
		{
			AddToastError
				(message: Resources.Messages.Errors.IdIsNull);

			return RedirectToPage(pageName: "Index");
		}

		try
		{

			var res = (await UserApplication.DeleteUser(id.Value));

			if (res.Succeeded == false ||
				res.ErrorMessages.Count() > 0)
			{
				foreach (var item in res.ErrorMessages)
				{
					AddToastError(item);
				}

				return Page();
			}

			var successMessage = string.Format
				(Resources.Messages.Successes.Deleted,
				Resources.DataDictionary.User);

			AddToastSuccess(message: successMessage);

			return RedirectToPage(pageName: "Index");

		}
		catch (System.Exception ex)
		{
			Logger.LogError
				(message: Constants.Logger.ErrorMessage, args: ex.Message);

			AddToastError
				(message: Resources.Messages.Errors.UnexpectedError);

			return RedirectToPage(pageName: "Index");
		}

	}
}

Server/Pages/User/Card/Index.cshtml.cs
using Application.ProductApp;
using Application.SaleApp;
using Application.TransportCostApp;
using Domain.CategoryAgg;
using Domain.ProductAgg;
using Domain.SaleAgg;
using Domain.TotalSaleAgg;
using Domain.Users;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Persistence;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using ViewModels.Pages.Admin.Sales;
using zarinpalasp.netcorerest.Models;

namespace Server.Pages.User.Card;

[Authorize]
public class IndexModel : BasePageModel
{
    private readonly ITotalSaleRepository _totalSale;

    private readonly ISaleApplication _application;

    private readonly IProductApplication _product;

    private readonly ISaleRepository _sale;

    public readonly DatabaseContext _context;

    private readonly HttpClient _httpClient;

    private readonly IWebHostEnvironment _webHostEnvironment;

    public readonly ITransportCostApplication _transportCost;

    public IndexModel(ITotalSaleRepository totalSale,
                      DatabaseContext context,
                      ISaleRepository sale,
                      ISaleApplication application,
                      IProductApplication product,
                      ITransportCostApplication transportCost,
                      IWebHostEnvironment webHostEnvironment)
    {
        _sale = sale;
        _product = product;
        _context = context;
        _totalSale = totalSale;
        _application = application;
        _transportCost = transportCost;
        _webHostEnvironment = webHostEnvironment;
        ViewModel = new();
        ViewModelSale = new();
        Sales = new();
        _httpClient = new HttpClient();
        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

    }

    public string merchant { get; set; }

    public string amount { get; set; }

    public string authority { get; set; }

    public string description { get; set; }

    public string callbackurl { get; set; }

    public Guid UserId { get; set; }

    public TotalSale ViewModel { get; set; }

    public List<Sale> Sales { get; set; }

    [BindProperty]
    public UpdateViewMode ViewModelSale { get; set; }

    public Product ViewModelProduct { get; set; }

    public int? pricetotal { get; set; } = 0;

    public int weighttotal { get; set; } = 0;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id.HasValue == false)
        {
            AddToastError
                (message: Resources.Messages.Errors.IdIsNull);

            return RedirectToPage(pageName: "Index");
        }

        UserId = id.Value;

        Sales = await _context.Sales.Where(x => x.UserId == UserId).ToListAsync();

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id, string check)
    {
        UserId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id").Value);

        if (id.HasValue == false)
        {
            AddToastError(Resources.Messages.Errors.IdIsNull);
            return Page();
        }

        ViewModelSale.Id = id.Value;
        var sale = await _context.Sales.FirstOrDefaultAsync(x => x.Id == ViewModelSale.Id);
        ViewModelProduct = await _context.Products.FirstOrDefaultAsync(x => x.Id == sale.ProductId);

        if (ViewModelSale.Number == 1 && check == "low")
        {
            await _application.DeleteSale(ViewModelSale.Id.Value);
        }

        if (check == "add")
        {
            var category = await _context.Categories.FirstOrDefaultAsync(x => x.Id == ViewModelProduct.CategoryParent_Id);

            if (category.Name == Resources.DataDictionary.Free)
            {
                var checksalefree = await _context.Sales.FirstOrDefaultAsync(x => x.UserId == UserId && x.ProductId == ViewModelProduct.Id);
                var checktotalsalefree = await _context.Sales.FirstOrDefaultAsync(x => x.UserId == UserId && x.ProductId == ViewModelProduct.Id);

                if (checksalefree != null && checksalefree.Number >= 5 && checktotalsalefree != null && checktotalsalefree.Number >= 5)
                {
                    AddToastError(message: Resources.Messages.Errors.Thisnumberofproductsisnotavailable);
                    return Page();
                }
            }

            ViewModelSale.Number = ViewModelSale.Number + 1;
            if (ViewModelSale.Number >= ViewModelProduct.Min_Major)
            {
                ViewModelSale.Price = ViewModelProduct.Discount_Major;
            }
            if (ViewModelSale.Number < ViewModelProduct.Min_Major)
            {
                ViewModelSale.Price = ViewModelProduct.Discount_Single;
            }
            await _application.UpdateSale(ViewModelSale);
        }

        if (check == "low")
        {
            ViewModelSale.Number = ViewModelSale.Number - 1;
            if (ViewModelSale.Number >= ViewModelProduct.Min_Major)
            {
                ViewModelSale.Price = ViewModelProduct.Discount_Major;
            }
            if (ViewModelSale.Number < ViewModelProduct.Min_Major)
            {
                ViewModelSale.Price = ViewModelProduct.Discount_Single;
            }
            await _application.UpdateSale(ViewModelSale);
        }

        return Page();
    }

    public async Task<IActionResult> OnPostCreateAsync()
    {
        int price = 0;

        int weight = 0;

        UserId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id").Value);

        var user = await _context.Users.FirstOrDefaultAsync(x => x.Id == UserId);

        if (user.Address == null || user.ProvinceAddress == null || user.CityAddress == null ||
            user.CellPhoneNumber == null)
        {
            return RedirectToPage("/Account/User/Update");
        }

        var sales = await _context.Sales
            .Where(x => x.UserId == UserId)
            .AsNoTracking()
            .ToListAsync();

        foreach (var item in sales)
        {
            //var product = await _context.Products.FirstOrDefaultAsync(x => x.Id == item.ProductId);
            var product = (await _product.GetProduct(item.ProductId)).Data;
            if (item.Number <= product.Number)
            {
                var weights = product.Weight;
                weights = weights * item.Number;
                weight = weight + weights;
                int sum = item.Price.Value * item.Number;
                price = price + sum;
            }
        }

        var transportcost = (await _transportCost.GetByWeight(weight)).Data;

        price = price + transportcost.Price;

        price = price * 10;

        //int max = 0;

        //Random random = new Random();
        //int tracking = random.Next(100000, 999999);

        //var check = _context.TotalSales.ToList();

        //if (check.Count != 0)
        //{
        //    max = _context.TotalSales.Max(x => x.FactorNumber);
        //}

        //bool a = false;

        //foreach (var item in sales)
        //{
        //    var product = (await _product.GetProduct(item.ProductId)).Data;

        //    if (item.Number <= product.Number)
        //    {
        //        product.Number = product.Number - item.Number;
        //        var _saleModel = new TotalSale
        //        {
        //            Color = item.Color,
        //            Number = item.Number,
        //            Products = item.ProductId,
        //            UserId = item.UserId,
        //            TotalPrice = item.Price,
        //            FactorNumber = max + 1,
        //            TrackingCode = tracking.ToString(),
        //        };

        //        _sale.Remove(item);

        //        await _totalSale.CreateAsync(_saleModel);

        //        await _product.UpdateProduct(product);

        //        a = true;
        //    }
        //}

        //await _sale.SaveChangesAsync();
        //await _totalSale.SaveChangesAsync();

        //if (a == true)
        //{
        //    int factor = max + 1;

        //    var stringContent = new FormUrlEncodedContent(new[]
        //    {
        //        new KeyValuePair<string, string>("Token","7TEEwvtO5H4AYUgnPttu6X9m6i0ix02V"),
        //        new KeyValuePair<string, string>("To",$"{user.CellPhoneNumber}"),
        //        new KeyValuePair<string, string>("Message",$"{Resources.Messages.Successes.Youritemhasbeenregistered} {Resources.DataDictionary.FactorNumber} : {factor}"),
        //        new KeyValuePair<string, string>("Sender","238")
        //    });

        //    var postTask = _httpClient.PostAsync("http://panelyab.com/api/send", stringContent);
        //    postTask.Wait();

        //    var response = postTask.Result;
        //    if (response.IsSuccessStatusCode)
        //    {
        //        response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
        //        var readTask = response.Content.ReadAsAsync<SendOutputModel>();
        //        readTask.Wait();

        //        var sendOutputModel = readTask.Result;
        //        if (sendOutputModel.Status == 100)
        //        {
        //            AddToastSuccess(Resources.Messages.Successes.Yourorderhasbeenregistered);
        //            //return RedirectToPage("/Index");
        //            return RedirectToPage("/CheckOrder");
        //        }
        //    }

        //    AddToastSuccess(Resources.Messages.Successes.Yourorderhasbeenregistered);
        //}

        //try
        //{

        //    using (var client = new HttpClient())
        //    {
        //        amount = $"{price}";

Server/Pages/User/Card/Index.cshtml
@page
@model Server.Pages.User.Card.IndexModel
@{
    var pagetitle = Resources.DataDictionary.Card;

    ViewData["pagetitle"] = pagetitle;

    Layout = "Layouts/Ltr/_Layout";

    // var Sales = Model._context.Sales.Where(x => x.UserId == Model.UserId).ToList();
}

<br />
<br />
<br />
<br />

<div class="container">
    <div class="row mt-2">
        <div class="col-md-8 p-2">
            @if (Model.Sales.Count == 0)
            {
                <div class="border rounded-1 p-5 text-center">
                    <h1>سبد خالیه!</h1>
                </div>
            }
            @if (Model.Sales.Count != 0)
            {
                <div class="border rounded-1 p-2">
                    @foreach (var item in Model.Sales)
                    {
                        Model.ViewModelSale.Number = item.Number;

                        var product = Model._context.Products.FirstOrDefault(x => x.Id == item.ProductId);
                        var pic = Model._context.ProductsPic.FirstOrDefault(x => x.Product_Id == product.Id);
                        var category = Model._context.Categories.FirstOrDefault(x => x.Id == product.CategoryParent_Id);

                        int? totalprice = (item.Price * item.Number);

                        int totalweight = (product.Weight * item.Number);

                        decimal price = decimal.Parse(totalprice.ToString(), System.Globalization.NumberStyles.Currency);

                        if (item.Number <= product.Number)
                        {
                            int? sum = Model.pricetotal.Value + totalprice;

                            Model.weighttotal = Model.weighttotal + totalweight;

                            Model.pricetotal = int.Parse(sum.ToString(), System.Globalization.NumberStyles.Currency);
                        }

                        <div class="row">
                            <div class="col-md-6 my-2">
                                @if (pic == null)
                                {
                                    <img width="100%" height="300" src="~/images/download.png" class="rounded-3" alt="@(product.Name_Product)">
                                }
                                @if (pic != null)
                                {
                                    <img width="100%" height="300" src="~/ProductPic/@(pic.PicAddress1)" class="rounded-3" alt="@(product.Name_Product)">
                                }
                            </div>
                            <div class="col-md-6 my-2">
                                <div class="w-100 rounded-2 bg-danger p-2 text-white mb-2">
                                    <div class="row">
                                        <div class="col-9">
                                            <h3>@(product.Name_Product)</h3>
                                        </div>
                                        @if (item.Number <= product.Number)
                                        {
                                            <div class="col-3">
                                                <p class="text-light">@(Resources.DataDictionary.Available)</p>
                                            </div>
                                        }
                                        @if (item.Number > product.Number)
                                        {
                                            <div class="col-3">
                                                <p class="text-light">@(Resources.DataDictionary.Unavailable)</p>
                                            </div>
                                        }
                                        <div class="col-12">
                                            <h6 class="text-light">@(category.Name)</h6>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <h5>@(Resources.DataDictionary.Gender) : @(product.Gender)</h5>
                                        <h5>@(Resources.DataDictionary.Type) : @(product.Type)</h5>
                                    </div>
                                    <div class="col-6">
                                        <h5>@(Resources.DataDictionary.Number) : @(item.Number)</h5>
                                        <h5>@(Resources.DataDictionary.PriceTotal) : @(price.ToString("#,#"))</h5>
                                    </div>
                                    <div class="col-12">
                                        <div class="row">
                                            @*<div class="col-6">
                                                <br />
                                                <br />
                                                <form method="post" asp-page-handler="Delete">
                                                    <button type="submit" asp-route-id="@(item.Id)" class="btn btn-danger">@(Html.DtatGetIconDelete()) @(Resources.ButtonCaptions.Delete)</button>
                                                </form>
                                            </div>*@
                                            <div class="col-6">
                                                <br />
                                                <br />
                                                <form method="post" >
                                                    <div class="input-group mb-3 w-100">
                                                        <button asp-route-id="@(item.Id)" asp-route-check="Add" type="submit" class="btn btn-outline-danger rounded-3">+</button>
                                                        <input asp-for="ViewModelSale.Number" value="@(Model.ViewModelSale.Number)" type="number" class="form-control rounded-3 text-center" readonly>
                                                        <button asp-route-id="@(item.Id)" asp-route-check="Low" type="submit" class="btn btn-outline-danger rounded-3">-</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr />
                    }
                </div>
            }
        </div>
        <div class="col-md-4 p-2">
            @if (Model.Sales.Count != 0)
            {
                var transportcost = (await Model._transportCost.GetByWeight(Model.weighttotal)).Data;

                int pricecost = int.Parse(transportcost.Price.ToString(), System.Globalization.NumberStyles.Currency);

                int sum = transportcost.Price + Model.pricetotal.Value;

                int totalprice = int.Parse(sum.ToString(), System.Globalization.NumberStyles.Currency);

                <div class="border rounded-1 p-2">
                    <h6><i class="bi bi-tag"></i> @(Resources.DataDictionary.Price) : @(Model.pricetotal.Value.ToString("#,#")) تومان</h6>
                    <h6><i class="bi bi-truck"></i> @(Resources.DataDictionary.ShippingCost) : @(pricecost.ToString("#,#")) تومان</h6>
                    <h6><i class="bi bi-cash"></i> @(Resources.DataDictionary.PriceTotal) : @(totalprice.ToString("#,#")) تومان</h6>

                    <form method="post" asp-page-handler="Create">
                        <button type="submit" class="w-100 btn btn-danger">@(Resources.DataDictionary.Order)</button>
                    </form>
                    <form method="post" asp-page-handler="Delete">
                        <!-- Button trigger modal -->
                        <button type="button" class="mt-2 w-100 btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            <i class="bi bi-trash"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        @* <h5 class="modal-title" id="exampleModalLabel">سیبت</h5> *@
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        آیا از خالی کردن سبد خرید خود مطمئن هستید؟
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="w-25 btn btn-outline-danger" data-bs-dismiss="modal">@(Resources.ButtonCaptions.Cancel)</button>
                                        <button type="submit" class="w-25 btn btn-danger">@(Resources.ButtonCaptions.Delete)</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>
</div>